name: Deploy AdonisJS to Azure

on:
  push:
    branches:
      - main
      - feat/workflow
  pull_request:
    branches:
      - main

jobs:
  apply-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "PORT=3333" >> $GITHUB_ENV
          echo "HOST=illusion-adonis-api.azurewebsites.net" >> $GITHUB_ENV
          echo "LOG_LEVEL=info" >> $GITHUB_ENV
          echo "APP_KEY=thisisappkeytest" >> $GITHUB_ENV
          echo "NODE_ENV=development" >> $GITHUB_ENV
          echo "DB_HOST=illusionadmin.postgres.database.azure.com" >> $GITHUB_ENV
          echo "DB_PORT=5432" >> $GITHUB_ENV
          echo "DB_USER=illusion" >> $GITHUB_ENV
          echo "DB_PASSWORD=Illusion" >> $GITHUB_ENV
          echo "DB_DATABASE=illusion_db" >> $GITHUB_ENV
          echo "SMTP_HOST=127.0.0.1" >> $GITHUB_ENV
          echo "SMTP_PORT=1025" >> $GITHUB_ENV

      - name: Run migrations
        run: node ace migration:run
        env:
          NODE_ENV: development
          DB_CONNECTION: pg
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: 5432
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB_NAME: ${{ secrets.PG_DB_NAME }}

      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: development
          DB_CONNECTION: pg
          PG_HOST: ${{ secrets.PG_HOST }}
          PG_PORT: 5432
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_DB_NAME: ${{ secrets.PG_DB_NAME }}

  # build-and-deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: 'npm'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Build AdonisJS
  #       run: npm run build

  #     - name: Deploy to Azure
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
  #         slot-name: production
  #         publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
